name: Angular-CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21'

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            ./GUI/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Install Angular project dependencies
        run: npm install
        working-directory: ./GUI

      - name: Build Angular Project
        run: npm run build
        working-directory: ./GUI

      - name: Run Angular Tests
        run: ./node_modules/.bin/ng test
        working-directory: ./GUI